services:
  web:
    container_name: koru-jekyll
    image: koru-jekyll:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_TOKEN=${NPM_TOKEN}
    volumes:
      - ./:/srv/jekyll
      - /srv/jekyll/node_modules
      - /srv/jekyll/build
    ports:
      - "4000:4000"
